### ISSUE TITLE
the convert example in Example.hs broken?

### ISSUE THREAD

**Issue by nushio3** [adamgundry/uom-plugin#1]
Hi, 

I am just surprised how the type checker plugin have changed the user experience of the type-level units. I have installed ghc 7.10.1 (over hsenv), uom-plugin and tried the examples. However, I found the conversion example not working:

```
(7.10.1)nushio@nuwheezy:uom-plugin-examples$ ghci Examples.hs 
GHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling Examples         ( Examples.hs, interpreted )
Ok, modules loaded: Examples.
> tenMetresInFeet 

<interactive>:2:1:
    No instance for (Data.UnitsOfMeasure.Singleton.KnownUnit
                       (Unpack (Base "ft")))
      arising from a use of ‘print’
    In a stmt of an interactive GHCi command: print it
> 
```

Do you have any idea what is going wrong? I'll to present any additional information needed, and help improve / add more examples.

**Comment by adamgundry** [comment]
Thanks for the report! I think the problem here is that GHCi does not have the plugin loaded, so it is not able to solve the constraints that arise from trying to `show tenMetresInFeet`. Try enabling it for interactive evaluation first:

```
:seti -fplugin Data.UnitsOfMeasure.Plugin
```

I find it useful to have the following in my `.ghci` file when working with `uom-plugin` interactively:

```
:seti -XDataKinds -XQuasiQuotes -XTypeOperators -fplugin Data.UnitsOfMeasure.Plugin
```

I'll try to document this a bit more clearly. Suggestions for improved or better examples are very welcome - `uom-plugin-examples` is very thin on the ground at the moment!

**Comment by nushio3** [comment]
Hi Adam, thank you for your quick response!

However, my example is still failing with the same error, after the addition of `:seti -fplugin Data.UnitsOfMeasure.Plugin` .

Here is my minimum not-working example:

https://gist.github.com/nushio3/4b6ac221d46bb52a101c

Do you have any idea?

**Comment by adamgundry** [comment]
This is another slightly under-documented corner, thanks for picking up on it. :smile:

Units need to be declared before they are used, otherwise this happens. Unfortunately it's not currently possible to define them in GHCi (that should change) so the easiest thing is either to import `Data.UnitsOfMeasure.Defs` or another module (such as `Examples`) that includes a top-level definition of the units involved.

**Comment by nushio3** [comment]
Hi, thank you for your advice! Now I have my example working.

https://gist.github.com/nushio3/0d01c4672982ceaf7e2f

**Comment by nushio3** [comment]
Now I know why it didn't work!

https://gist.github.com/nushio3/25b52e6f6365d777bbcd

https://gist.github.com/nushio3/506ce59ea67c719c2c09
