### ISSUE TITLE
Dimensionless units

### ISSUE THREAD

**Issue by expipiplus1** [adamgundry/uom-plugin#14]
Would it be worth putting dimensionless SI units (such as radians or steradians) in Defs.hs?

Would it implementation differ in any way from how other units are defined?

**Comment by nushio3** [comment]
There have been long debate on whether angles are its own units or not. Based on my personal experience I vote for angle units :+1: 

Because, dimensionless angle units are helpful in distinguishing quantities in radio astronomy:
https://en.wikipedia.org/wiki/Radiance#SI_radiometry_units
Adding radiant flux to radiant intensity does not make sense, and it is the kind of mistake unit systems are to prevent.

**Comment by adamgundry** [comment]
I agree that it makes sense to treat them as separate base units. It might be useful if they were convertible with other dimensionless units, but that requires a fix to #4.

**Comment by expipiplus1** [comment]
@adamgundry, would that allow doing things like the following?

``` haskell
angularSpeed :: [u|rad/s|]
angularSpeed = convert x
  where x :: [u|s^-1|]
        x = undefined
```

At the moment I'm doing this this way:

``` haskell
angularSpeed :: [u|rad/s|]
angularSpeed = [u|1rad|] *: x
  where x :: [u|s^-1|]
        x = undefined
```

**Comment by adamgundry** [comment]
Yes, it turns out that it does! Thanks for the test case.

**Comment by expipiplus1** [comment]
excellent, thanks!
